### ISSUE TITLE
記事のmetadata部分の書式の崩れ

### ISSUE THREAD

**Issue by nadare881** [future-architect/tech-blog#1227]
以下の記事について、最初の---が抜けています。

https://github.com/future-architect/tech-blog/blob/master/source/_posts/20211007a_Java17%E5%AF%BE%E5%BF%9C%E7%89%88%EF%BC%81Java%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84%E3%81%AE%E7%B4%B9%E4%BB%8B.md

**Comment by nadare881** [comment]
以下の記事について、dateの部分に"2021/09/13 00:00:00z"とzが入っています
https://github.com/future-architect/tech-blog/blob/master/source/_posts/20210913a_%E3%80%90Google_Chat_API%E3%80%91Incoming_Webhook_%E3%82%92_Go_%E3%81%A7%E8%A7%A6%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%8B.md

**Comment by ma91n** [comment]
対応しました！
