### ISSUE TITLE
"lede"の表記ゆれ

### ISSUE THREAD

**Issue by nadare881** [future-architect/tech-blog#1229]
以下の二つの記事について、"lede"が"lade"になっています。
https://github.com/future-architect/tech-blog/blob/master/source/_posts/20160217_LT%E5%A4%A7%E4%BC%9A%E5%89%8D%E7%B7%A8.md
https://github.com/future-architect/tech-blog/blob/master/source/_posts/20160218-LT%E5%A4%A7%E4%BC%9A%E5%BE%8C%E7%B7%A8.md

**Comment by ma91n** [comment]
@nadare881 ありがとうございます。修正しました。

https://github.com/future-architect/tech-blog/commit/f3a6c9b6b5a239bd28c7a4c4af66f7b4802b3267#diff-6c5f1d382c0c596a4505fb5895e765e9c477b0d6bb79a93eeb028a5342ac9fd2
https://github.com/future-architect/tech-blog/commit/55dfb80771fee9785ad8d402dbca9204bed01047#diff-66ff590e83f5704388db7a04fbeb5e1cfc8cf4655c07df1f90c3b1f699923c84
