### ISSUE TITLE
typo: cretae (20220202a_Pipenv+LocalStackで作るLambda開発環境.md)

### ISSUE THREAD

**Issue by ftnext** [future-architect/tech-blog#1344]
https://future-architect.github.io/articles/20220202a/ を興味深く読みました。
typoを見つけたので共有します。
cretae -> create

https://github.com/future-architect/tech-blog/blob/c99d97c3339f01e5b3c62e68b1bfec98f8641b63/source/_posts/20220202a_Pipenv%2BLocalStack%E3%81%A7%E4%BD%9C%E3%82%8BLambda%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83.md#L583

「cretae」でリポジトリを検索したところ、2022/02/04の記事にも見つかりました。

https://github.com/future-architect/tech-blog/blob/c99d97c3339f01e5b3c62e68b1bfec98f8641b63/source/_posts/20220204a_Step_Functions%E3%81%AE%E5%8B%95%E7%9A%84%E4%B8%A6%E5%88%97%E5%87%A6%E7%90%86%E3%82%92%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E3%81%A7%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B.md#L668

**Comment by ma91n** [comment]
ご指摘ありがとうございます、対応します。
