### ISSUE TITLE
「Lambda×Go並列処理で100万回APIを呼び出す」記事についての問い合わせ

### ISSUE THREAD

**Issue by ddddddO** [future-architect/tech-blog#1427]
futureさんの記事をよく参考にさせて頂いております。
「[Lambda×Go並列処理で100万回APIを呼び出す](https://future-architect.github.io/articles/20220516a/)」の記事も、面白く読ませてもらいました🙇

記事中のサンプルコードでgoroutineの同時実行数の制御をsemaphoreチャネルで制御している箇所があります。
semaphoreチャネルから値をデキューする処理を、goroutine内の処理の終わりかdeferでしないと機能しなさそうと思い、挙動を見てみました([こちら](https://go.dev/play/p/NC0p_HZeW5Z))。

デキューする処理もサンプルコードにあるといいかと思いissueを立てました。よろしくお願いします🙏

```go
var wg sync.WaitGroup
semaphore := make(chan struct{}, 500)
for _, line := range lines {
    semaphore <- struct{}{}
    wg.Add(1)
    go func(wg *sync.WaitGroup, line CsvLine) {
        defer wg.Done()
        if err := postRequest(ctx, line); err != nil {
            log.Printf("post request error: %v", err)
        }
    }(&wg, line)
}
wg.Wait()
```

**Comment by ma91n** [comment]
@ReoGoto ご指摘＆コードサンプル、ありがとうございます。
担当者に連絡して修正したしました

**Comment by ddddddO** [comment]
お忙しいところ、ご対応ありがとうございました🙇
